;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	hydra-multiple-cursors/ignore
	hydra-multiple-cursors/mc/add-cursor-on-click
	))

(setq mc/cmds-to-run-once
      '(
	hydra-multiple-cursors/hydra-pop-and-exit
	))
